name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6]
        env: [CI]
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/checkout@v2

    - name: 'set ENV'
      run: echo "${{ matrix.env }}=1" >> $GITHUB_ENV

    - name: Install missing libs
      run: |
        sudo apt-get -yqq install libsqlite3-dev

    - name: Install gems
      env:
        RAILS_VERSION: "5.2"
      run: |
        bundle install

    - name: Test
      env:
        RAILS_VERSION: "5.2"
      run: |
        bundle exec rake
